// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/pantyukhov/imageresizeserver/services"
	"github.com/pantyukhov/imageresizeserver/transport"
)

// Injectors from wire.go:

func InitializeTransport() transport.Transport {
	s3Service := services.NewS3Service()
	fileHandler := transport.NewFileHandler(s3Service)
	transportTransport := transport.NewTransport(fileHandler)
	return transportTransport
}
